In [34]:
# Numpy是对数组的操作，列表与数组的区别在于，
# 列表的每一项都是一个对象，指向判断这个项是什么类型和位置，而数组的每一项指向的是一个已知类型的项，且这个项的类型是固定的

In [35]:
# import numpy
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [36]:
# 通过内置模块创建一个数组
import array
L = list(range(1,10))
print(array.array('i',L))

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])


In [37]:
# 通过Python列表创建一个数组
import numpy as np
print(np.array([1,2,3,4,5,6,7,8,9]))
print(np.array([3.1415926,6,9,8,6]))
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[1 2 3 4 5 6 7 8 9]
[3.1415926 6.        9.        8.        6.       ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# 从头创建数组
# 创建一个值都为0的数组
print(np.zeros(9,dtype='int'))
print(np.zeros((3,),dtype='int'))
print(np.zeros((1,3),dtype='int'))
print(np.zeros((3,3),dtype='int'))
print(np.zeros(9,dtype='float'))
# 创建一个值都为0的数组
print(np.ones(9,dtype='int'))
print(np.ones((3,),dtype='int'))
print(np.ones((1,3),dtype='int'))
print(np.ones((3,3),dtype='int'))
print(np.ones(9,dtype='float'))
# 创建一个值是任意的数组
print(np.full(9,1,dtype='int'))
print(np.full((3,),2,dtype='int'))
print(np.full((1,3),2,dtype='int'))
print(np.full((3,3),2,dtype='int'))
print(np.full(9,3,dtype='float'))
# 创建一个值是线性序列的数组
print(np.arange(9,12,dtype='int'))
print(np.arange(9,20,dtype='float'))
# 均匀分配到的数组
print(np.linspace(0,1,6))
# 0-1随机组成的数组
print(np.random.random((3,4)))
print(np.random.random(3))
# 正态分布数组，均值为0，方差为1的
print(np.random.normal(0,1,(3,4)))
print(np.random.normal(20,5,(3,3)))
print(np.random.normal(0,1,3))
# 整数数组
print(np.random.randint(0,10,(3,3),dtype='int'))
# print(np.random.randint(0,10,(3,3),dtype='float64'))  ## 报错
# 单位矩阵
print(np.eye(5,dtype='int'))
print(np.eye(5,dtype='float'))
# 未初始化的数组
print(np.empty(3))
print(np.empty(9,dtype='int'))
print(np.empty((3,3),dtype='float'))

[0 0 0 0 0 0 0 0 0]
[0 0 0]
[[0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1]
[1 1 1]
[[1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1]
[2 2 2]
[[2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[3. 3. 3. 3. 3. 3. 3. 3. 3.]
[ 9 10 11]
[ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[0.  0.2 0.4 0.6 0.8 1. ]
[[0.56343868 0.81079709 0.20710816 0.77290485]
 [0.88192932 0.34964067 0.78354505 0.1860158 ]
 [0.52420292 0.60593281 0.50011832 0.32157877]]
[0.88152986 0.12067935 0.16949882]
[[-0.62437994 -0.18064985 -0.35765015 -0.38879569]
 [-0.12246466 -0.21340388  0.28366744 -0.18085761]
 [-1.34640266 -0.75272859  0.08302981 -0.56446151]]
[[24.74296503 14.18964563 26.00362775]
 [18.32789842 19.91516959 22.58245334]
 [20.8422788  21.9811531  30.05721312]]
[ 1.886146   -0.94330768  0.1132451 ]
[[0 5 5]
 [5 7 9]
 [7 7 0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0